# Generated by Django 4.2.6 on 2023-10-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnnapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadImage',
            new_name='UploadedImage',
        ),
    ]
